### ISSUE TITLE
chore: move the header into its own component

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/seeit#17]

**Comment by EmmanuelArowoselu** [comment]
I am interested in this issue

**Comment by Dharmik48** [comment]
Okay, I will assign you for this.

**Comment by mdazad1508** [comment]
@Dharmik48 i have already done this .. could you please check my PR

**Comment by Dharmik48** [comment]
> I am interested in this issue

Hey @Emmanuel527, I am extremely sorry as @mdazad1508 solved this issue. You can check out issues in my other project to contribute.

**Comment by Dharmik48** [comment]
And @mdazad1508, you should have first checked if the issue is already assigned to someone else. 

If no one is assigned then you can raise a PR for it. Please be careful next time.

**Comment by mdazad1508** [comment]
extremly sorry @Dharmik48 and @Emmanuel527 , will take care of this from next time.
