### ISSUE TITLE
style: move the flash message to the bottom

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/seeit#20]

**Comment by opelolo** [comment]
Hi, please can you assign this issue to me if it is not fixed yet? I'm new to open source and would love to contribute

**Comment by Dharmik48** [comment]
Hey @opelolo, it is great to see you that are interested to contribute in to open source!🚀

But unfortunately, this issue has been fixed.😔

🎉Though, there are more issues you can work on, checkout out: 

- https://github.com/Dharmik48/seeit/issues/3
- https://github.com/Dharmik48/quizzical/issues/11
- https://github.com/Dharmik48/quizzical/issues/8

Check them out add tell me if you are interested in any of them. Or if you don't find any of them interesting then you can raise your own issues in any of my reports! I will be happy to have you as a contributor🤗
