### ISSUE TITLE
doc: improve README

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/seeit#3]
We need to add a proper README to the project

**Comment by JScrips** [comment]
I'll help

**Comment by Dharmik48** [comment]
That would be very great! Thank you so much!

**Comment by KendallDoesCoding** [comment]
Hi, why did you unassign @JScrips?

**Comment by Dharmik48** [comment]
Yes its been more than 10 days now so I unassigned him.

**Comment by KendallDoesCoding** [comment]
You can ping him for a update. Don't just assign like that lol

**Comment by Dharmik48** [comment]
> You can ping him for a update. Don't just assign like that lol

You are right😅 I should have pinged him first

**Comment by JScrips** [comment]
> > You can ping him for a update. Don't just assign like that lol
> 
> You are right😅 I should have pinged him first

Hello Dharmik and Kendall, 

Thank you @KendallDoesCoding for your consideration and empathy. I really appreciate it. @Dharmik48 I apologize for my absence, I have run into some real-life things on my end. I understand your reasoning for unassigning me, I should've pinged you sooner to give an update. So for that, I apologize

**Comment by Dharmik48** [comment]
> Thank you @KendallDoesCoding for your consideration and empathy. I really appreciate it. @Dharmik48 I apologize for my absence, I have run into some real-life things on my end. I understand your reasoning for unassigning me, I should've pinged you sooner to give an update. So for that, I apologize

No need to apologize, I should have pinged you before unassigning you. 

I have reassigned you.
