### ISSUE TITLE
Image processing takes too long

### ISSUE THREAD

**Issue by KendallDoesCoding** [Dharmik48/seeit#31]
To process the image before uploading, it takes very long, it should be instant :)

**Comment by Dharmik48** [comment]
Yeah I know that's an issue, I am new to Firebase so I don't know if there's any way to speed up the process.

Do you know how to fix that?

**Comment by KendallDoesCoding** [comment]
> Yeah I know that's an issue, I am new to Firebase so I don't know if there's any way to speed up the process.
> 
> Do you know how to fix that?

Nope, even I'm new to firebase lol

**Comment by Dharmik48** [comment]
We will have to do some research for it, or wait for someone who knows how to solve it
