### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/seeit#34]
We need someone who can design a simple favicon and set it up for the website.

If you don't know how to design a favicon, then use something similar to "👀"

**Comment by realJema** [comment]
I created a pull request to fix issue, kindly review

**Comment by KendallDoesCoding** [comment]
Better to create a discussion for this instead of an issue.

**Comment by Dharmik48** [comment]
> I created a pull request to fix issue, kindly review

Yes, I saw the PR and suggested a change. Please have a look.

**Comment by Dharmik48** [comment]
> Better to create a discussion for this instead of an issue.

Yeah maybe we should but I don't want to over-complicate this matter, and just go with the `👀` as a favicon.

**Comment by KendallDoesCoding** [comment]
Sure. that works too!!!

**Comment by deeproop** [comment]
Hey, I created a pull request. Hope it resolves the issue :)

**Comment by Dharmik48** [comment]
> Hey, I created a pull request. Hope it resolves the issue :)

It's good to have you as a contributor @deeproop! But @realJema is already working on this issue so we will not be able to merge your PR😔

Why don't you check out other issues which are yet not assigned to anyone?

**Comment by deeproop** [comment]
Not a problem, I will check other issues :)
