### ISSUE TITLE
add loader when app is fetching data from db

### ISSUE THREAD

**Issue by pokhrelanmol** [Dharmik48/seeit#43]
it feels weird when you go to the site and it only has a logo when its first renders. so to improve UX add a loader when app is fetching data from db

**Comment by Dharmik48** [comment]
That's a great idea to improve the UX @pokhrelanmol!

Would you like to work on this?

**Comment by pokhrelanmol** [comment]
Ya would love to

**Comment by pokhrelanmol** [comment]
hey dharmik, I have pushed the code to fix this issue but I don't see the button to send you a pull request. I think you need to reject or merge my previous pull requests to resolve this issue.

**Comment by Dharmik48** [comment]
> hey dharmik, I have pushed the code to fix this issue but I don't see the button to send you a pull request. I think you need to reject or merge my previous pull requests to resolve this issue.

Yes, you'll need to create a new PR with only the changes that solve this issue. 

Your previous PR also has those other changes regarding the _Flash_ message issue. So raise a new PR with changes only of this issue so I can merge it🚀

**Comment by pokhrelanmol** [comment]
my branch is already 3 commits ahead of the main which includes the flash message solution also. do I need to revert the changes and send a new PR with only a solution for the issue assigned to me or i can just send a PR with the all changes made by me including the flash message?

**Comment by Dharmik48** [comment]
> my branch is already 3 commits ahead of the main which includes the flash message solution also. do I need to revert the changes and send a new PR with only a solution for the issue assigned to me or i can just send a PR with the all changes made by me including the flash message?

You will need to send a new PR with only a solution for _this issue_. It should not contain all the changes.
