### ISSUE TITLE
Add home link to logo

### ISSUE THREAD

**Issue by Khyati41** [Dharmik48/seeit#46]

**Comment by Dharmik48** [comment]
Would you like to work on this issue?

**Comment by Khyati41** [comment]
Yes

**Comment by Dharmik48** [comment]
Alright! I'll assign this to you!

**Comment by AngeloTree** [comment]
Hey, I am interested in working on this task!

**Comment by Dharmik48** [comment]
> Hey, I am interested in working on this task!

I extremely sorry @AngeloTree, but the issue is already assigned to @Khyati41.

You can check out other issues on any of these repos which are not assigned to anyone yet:

- https://github.com/Dharmik48/notes-react-firebase-v2.0/issues
- https://github.com/Dharmik48/todo-list-app/issues

**Comment by pokhrelanmol** [comment]
why this issue is still not resolved ?

**Comment by Dharmik48** [comment]
> why this issue is still not resolved ?

Oh, my bad😅 I forgot to close this issue, Thanks for the reminder!
