### ISSUE TITLE
Isolate authentication logic

### ISSUE THREAD

**Issue by pokhrelanmol** [Dharmik48/seeit#48]
we have our auth logic inside the app.jsx and that's fine for the small project but if we want to scale, then I think we need to isolate the auth logic and set loggedIn user  in a global user context so we can refer to it anywhere without worrying about prop drilling issue.

**Comment by mobo07** [comment]
Hi, will it be okay if I achieve this with redux toolkit?

**Comment by Dharmik48** [comment]
> Hi, will it be okay if I achieve this with redux toolkit?

We don't want to go into the redux domain yet.

**Comment by Dharmik48** [comment]
> global user context

I think instead of context we should use a custom hook.

**Comment by pokhrelanmol** [comment]
ya, custom hook can be a good option but a custom hook alone can create problems in future. instead, we can combine react context and custom hook and that would probably solve the complete issue.
you can refer [this](https://github.com/pokhrelanmol/goat-marketplace/blob/main/src/contexts/userContext.tsx)  and [this](https://github.com/pokhrelanmol/goat-marketplace/blob/main/src/components/auth/Login.tsx)  to get the complete overview.

You can assign me this task.

**Comment by Dharmik48** [comment]
Looks good, I'll assign you then🚀
