### ISSUE TITLE
[FEATURE] <prefers-color-scheme: dark>

### ISSUE THREAD

**Issue by mati5kova** [Dharmik48/seeit#60]
### Description

Hello, I'd like to modify useDarkMode() hook so that it sets the default theme to be dark mode if the global (system) preference is dark theme. It would also react to a possible system change from dark to ligth theme.  

### Screenshots

![image](https://user-images.githubusercontent.com/77550206/186895734-a79482ff-6ec6-4c33-9a3f-3f1bb1655de8.png)
![image](https://user-images.githubusercontent.com/77550206/186895817-892a1499-e7e5-4342-b6d4-0bd47057deeb.png)

**Comment by Dharmik48** [comment]
That will be a great improvement! I'll assign you.
