### ISSUE TITLE
[FEATURE] Smooth scroll to comment section

### ISSUE THREAD

**Issue by mati5kova** [Dharmik48/seeit#68]
### Description

I think it would be great user experience if the page were to smooth scroll to comment section after clicking the comment button on a post. Reddit also does something similar.

If you think it would be a good feature just assign me.

### Screenshots

![image](https://user-images.githubusercontent.com/77550206/187091763-71550efd-1624-4c90-bc29-9586c0c78ccc.png)

**Comment by Dharmik48** [comment]
How exactly can we add smooth scrolling, as clicking on the comment button leads the users to an entirely new page?

**Comment by mati5kova** [comment]
Basically, when the page with the post and the comments loads it will scroll to the comment section. It can be done with a <HashLink>. I have already  implemented this, so I'll open a PR so you can check it out.
