### ISSUE TITLE
Add a light and dark mode toggle

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/seeit#7]
As of now, `SeeIt` only supports light mode. We need to add `dark mode` and a toggle to switch between light and dark mode.

**Comment by theabhayprajapati** [comment]
i am interested in this issue

**Comment by Dharmik48** [comment]
Thank you for showing your interest @theabhayprajapati! I will assign this to you 🚀

**Comment by Dharmik48** [comment]
Closed with #9
